"""add_enhanced_prompt_to_generation_history

Revision ID: d06d2bc2916b
Revises: 0001
Create Date: 2026-06-06 03:54:18.818462+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd06d2bc2916b'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_history', sa.Column('enhanced_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_history', 'enhanced_prompt')
    # ### end Alembic commands ###
